site_name: ESPECIALIZACIÓN EN FABRICACIÓN DIGITAL E INNOVACIÓN 
site_description: EFDI Documentation
site_author: Fab Lab Barcelona, UTEC
site_url: https://efdi-docs.github.io/efdi-page/
repo_name: efdi-page
repo_url: https://github.com/efdi-docs/efdi-page 
edit_uri: edit/main/docs/

nav:
  - Welcome!: 2023-24/index.md
  #- Faculty: https://utec.edu.uy/es/educacion/posgrado/especializacion-en-fabricacion-digital-e-innovacion/
  - Estudiantes:
    - student-websites/index.md
  - Previous Years:
    - Index: previous.md
  - Herramientas:
    - 2023-24/year-1/herramientas/index.md

theme:
  language: 'en'
  name: 'material'
  font:
    text: Space Grotesk
    code: Space Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - content.tabs.link
    - content.action.edit
    - content.code.copy
  custom_dir: 'custom_theme'
  palette:
    # See assets/stylesheets/extra.css file for the color definitions
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/crystal-ball
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: primary
      toggle:
        icon: material/weather-lightning
        name: Switch to dark mode
  logo: assets/mdef.svg
  favicon: assets/images/mdef-favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
extra_css:
  - assets/stylesheets/extra.css
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/fablabbcn'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/fablabbcn/'
    - icon: fontawesome/brands/github
      link: 'https://github.com/fablabbcn/mdef-docs'
  # project: ''
  fullscreen_button: false

plugins:
  - macros
  - search
  - open-in-new-tab
  - exclude:
      glob:
      - previous_years/*
      - 2023-24/year-1/t3/*
      - 2023-24/research-trip/*

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: ⇝
      toc_depth: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.extra

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
  - 'https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'
  - 'assets/javascripts/extra.js'
  - 'assets/javascripts/calendar.js'
  - 'assets/javascripts/google-drive.js'
